### ISSUE TITLE
Run Test Button is not usable

### ISSUE THREAD

**Issue by DavertMik** [codeceptjs/ui#101]
Run button should be moved closer to a test so running tests could be simplified

![image](https://user-images.githubusercontent.com/220264/102660890-805d0380-4184-11eb-8ee5-35a52e57979c.png)

**Comment by ArtemSilka** [comment]
Hey @DavertMik , I would like to take on this issue.

**Comment by DavertMik** [comment]
@ArtemSilka sure, it would be awesome if you could handle it. I think it will make UX much better!
