### ISSUE TITLE
CodeceptUI does not install or run on Mac with M1 Processor

### ISSUE THREAD

**Issue by rdherric** [codeceptjs/ui#124]
#### What are you trying to achieve?

- We would like to be able to use CodeceptUI on a Mac with an M1 processor.  We used the standard `npm install @codeceptjs/ui` command to install it.

#### What do you get instead?

- Running `npm i @codecept/ui` results in Electron 7.3.3 being installed, which does not install successfully on M1 processors.  
- This is a known issue with Electron: only versions 11.0.0+ will run on an M1 processor.
- CodeceptUI cannot be installed or used.

### Environment info

- MacBook Air with M1 processor

**Comment by henriqueuller** [comment]
Same here

**Comment by rdherric** [comment]
I happen to have updated the whole Project to use Electron 12.  I will make a PR.

**Comment by henriqueuller** [comment]
Thanks Robert, I appreciate it

**Comment by rdherric** [comment]
@henriqueuller - sorry this took a while.  Here is the PR if you would like to fork it or use it yourself:

https://github.com/codeceptjs/ui/pull/130

**Comment by DavertMik** [comment]
The Electron was updated so I hope it runs now
