### ISSUE TITLE
Next release date.

### ISSUE THREAD

**Issue by bnpatel1990** [codeceptjs/ui#165]
@DavertMik  @Arhell  I see there have been quite a few PRs merged in since the last release 7 months ago. When is the next release schedule for the UI??  [NPM](https://www.npmjs.com/package/@codeceptjs/ui/v/0.4.6)

**Comment by bnpatel1990** [comment]
@kaflan @DavertMik  - Just trying to bump the thread.

**Comment by pvarga00** [comment]
+1 to the bump :)

**Comment by ogarciacapetillo** [comment]
+1

**Comment by detrek77** [comment]
+1

**Comment by DavertMik** [comment]
Ups, looks I forgot to run npm publish.
I created a GitHub workflow to do that automatically. 
Now 0.4.6 release is out
Thanks for your patience!
