### ISSUE TITLE
CI/CD setup Netlify

### ISSUE THREAD

**Issue by kobenguyent** [codeceptjs/ui#257]
Hi @DavertMik what do you think if we could setup something similar? Pretty much the same techstack. 

Essentially, it would help us preview the PR faster as we don't need to run the code locally. 

Link to example: https://github.com/flawiddsouza/Restfox/pull/139

**Comment by DavertMik** [comment]
Sorry I don't understand how we can preview that without a backend and UI requires NodeJS backend to run
