### ISSUE TITLE
Get error after closing the code editor warning and refreshing the page

### ISSUE THREAD

**Issue by kobenguyent** [codeceptjs/ui#45]
#### What are you trying to achieve?

1. Open any test
2. Click Source
3. Click Edit button
4. Close the warning popup
5. Refresh the page

#### What do you get instead?

<img width="409" alt="Screenshot 2019-12-17 at 11 29 28" src="https://user-images.githubusercontent.com/7845001/70987780-e0782000-20c0-11ea-95eb-10086825c75d.png">

**Comment by seafoam6** [comment]
I get this too, if you just re-open http://localhost:3001 in a new tab you'll be back on the UI. Not a fix, but a simple work around.
