### ISSUE TITLE
Electron build

### ISSUE THREAD

**Issue by DavertMik** [codeceptjs/ui#62]
It would be nice if we could optionally run codecept-ui as Electron app.

Pros: 
* easy to start and manage this app
* more user friendly

Cons:
* dependency on electron (maybe have it optional)

Inside Electron app there must be two modes:

* full width - in this mode you see steps on the left and screenshots on the right. Useful when reviewing already executed tests or running tests in headless mode
* 1/3 width - in this mode the tests are running inside the browser window, so it is easy to have live preview in a real browser for tests.

So unlike our web app, electron app should also control its size and position (palce itself into top left corner and adjust size to modes)

**Comment by gulench** [comment]
https://github.com/codeceptjs/ui/blob/d3878a0462223ecb6b720fb7576916ae98e25743/lib/app.js#L29

@DavertMik, with the above `x` position, the electron app window falls outside of the desktop-viewport. Shouldn't `x` be set to *either* of the following:

- Left-align window: `x: 0,` 
- Right-align window: `x: (screenWidth - width),`

**Comment by DavertMik** [comment]
Thank you, @gulench 
I will try to implement it this way
