### ISSUE TITLE
Refactor Menu

### ISSUE THREAD

**Issue by DavertMik** [codeceptjs/ui#95]
CodeceptUI window is shown in two modes

* Full width - mode (server, or maximized app)
* Small size - for application mode, mobile, etc

In small size mode not all menu elements are shown. For instance, the Settings button is missing. We need to refactor Menu component to work for small and wide screens.

Small size (no Settings button)

![image](https://user-images.githubusercontent.com/220264/94868772-7f9db680-044c-11eb-8dbd-19c2283f14b7.png)

Full menu (with Settings)

![image](https://user-images.githubusercontent.com/220264/94868816-9512e080-044c-11eb-8aac-0fb1b60fefb9.png)

We may need more optoions in menu with PageObjects, Config, etc

**Comment by pavanjoshi914** [comment]
I would like to work on this thanks!

**Comment by geilix10** [comment]
Just created a [PR](https://github.com/codeceptjs/ui/pull/97) to solve this issue. #hacktoberfest
